- Makefile
- src/index.ml
This avoids calling lseek with negative values.
> call get_entry with valid offsets

- bench/main.ml
- src/index.ml
- src/index.mli
- test/unix/main.ml
For now this costs ~20% more time on insertions (merges included), and has shown no improvements for finds, thus marking as draft.
> Have only one index file

- bench/main.ml
- src/index.ml
- src/index.mli
- test/unix/main.ml
Breaking changes :
- `replace` becomes `add` since it's not replacing the old binding anymore.
- `find` becomes `find_all` since it returns all the values bound to a key.
> Allow duplicate keys

- src/index.ml
Now the fanout contains -1 everywhere when nothing was added to it and non negative numbers otherwise.
The issue was when some offsets are added to the fanout but some fans (at the begining of the fanout) remained empty, then we could get negative (-1) offsets when querying it.
> Don't allow negative offsets in the fanout

- src/index.ml
This was obviously very wrong.
Thanks @icristescu for spotting an issue with your new tests !
> Fix a typo when creating fan out on a readonly instance

- src/index.ml
On top of https://github.com/mirage/index/pull/14.
This PR improves performances of the `merge` function, by:
- Use an array and `Array.sort` instead of a set, to sort `log_mem`
- Precompute and store keys hash, the number of calls to `K.hash` went from 114 000 000 to 8 000 000 in the bench in `bench/`
- Avoid decoding and encoding entries, only the key need to be decoded
These improvements will be even more useful if `K.hash` is slow or if encoding/decoding values is costly.
Running the bench included in `bench/` with `index_size=3_000_000` and `log_size=500_000`, before:
```
Adding 3000000 bindings.
2999k/3000k
3000000 bindings added in 26.371166s.
Finding 3000000 bindings.
2999k/3000k
3000000 bindings found in 34.997058s.
```
after:
```
Adding 3000000 bindings.
2999k/3000k
3000000 …
```
> Improve merge speed

- src/index.ml
- src/index.mli
The `roots` table now searches by `(root, readonly)` instead of just `name`, and all instances are shared.
> Remove shared argument

- src/index.ml
Before:
```
...
Finding 3000000 bindings.
2999k/3000k
3000000 bindings found in 51.581994s.
...
```
After:
```
...
Finding 3000000 bindings.
2999k/3000k
3000000 bindings found in 43.150246s.
...
```
e.g. a bit less than ~15% improvements.
We are still doing too many reads (almost 2Go for a 170Mo file!) but way less than before (it used to be 16 Go).
Note that I've also fixed the `look_around` function to always stay between `low` and `high`.
> batch reads during searches

- src/unix/dune
- src/unix/index_unix.ml
- src/unix/pread.c
- src/unix/pwrite.c
This will allow to have concurrent read/write to the file without locking it.
Before:
```
$ dune exec -- bench/main.exe
Adding 3000000 bindings.
2999k/3000k
3000000 bindings added in 13.844343s.
Finding 3000000 bindings.
2999k/3000k
3000000 bindings found in 27.114155s.
```
After:
```
$ dune exec -- bench/main.exe
Adding 3000000 bindings.
2999k/3000k
3000000 bindings added in 13.672671s.
Finding 3000000 bindings.
2999k/3000k
3000000 bindings found in 24.104619s.
```
> use pread/pwrite instead of lseek

- src/index.ml
- src/index.mli
- src/search.ml
- src/search.mli
- test/dune
- test/search.ml
This provides the interpolation_search function with a cleaner abstraction of the underlying index as an array of elements linearly distributed according to some 'metric' (in this case, the key hash).
This simplifies the core of the interpolation search quite a bit, and allows it to be tested individually. Unfortunately, it needs rebasing over https://github.com/mirage/index/pull/39 which breaks the clean array abstraction I was going for.
> Use an Array abstraction within the interpolation search

- src/index.ml
- src/index.mli
- src/io_array.ml
- src/io_array.mli
- src/log.ml
- src/log.mli
- src/unix/index_unix.ml
- src/unix/index_unix.mli
- test/unix/dune
- test/unix/io_array.ml
- extracts `IOArray` to a separate `io_array.ml` file
- functorises `IOArray` on IO and an element type
- adds basic tests of `IOArray` behaviour (requires exposing `Index_unix.IO` under `Private`)
> Generalise IOArray on arbitrary IO / element types

- src/index.ml
- src/io.mli
- src/unix/index_unix.ml
Sometimes the os picks the same file descriptor, when closing and re-opening an index. It is not reliable to check if the file descriptor is still valid, to see if an index is closed or not.   
We can use the counter to check if an index is still alive.
> Replace valid file descriptor test with a check on counter

- test/unix/force_merge.ml
- test/unix/force_merge.mli
- test/unix/io_array.mli
- test/unix/main.mli
Adds a set of empty `.mil` files for the tests, to catch any unused values.
> Add empty .mli files for tests

- test/unix/force_merge.ml
- test/unix/force_merge.mli
- test/unix/io_array.ml
- test/unix/io_array.mli
- test/unix/main.ml
The goal is to get a cleaner test output, and more consistent test modules, exposing a `tests` value.
> Have only one Alcotest.run

- src/fan.ml
- test/fuzz/fan/main.ml
This increases the number of fans to get 4k large fans.
Before:
```
2999k/3000k
3000000 bindings added in 10.507509s.
Finding 3000000 bindings.
2999k/3000k
3000000 bindings found in 19.287851s (RW).
2999k/3000k
3000000 bindings found in 22.156307s (RO).
```
After (30% speedup in RW mode):
```
Adding 3000000 bindings.
2999k/3000k
3000000 bindings added in 10.506458s.
Finding 3000000 bindings.
2999k/3000k
3000000 bindings found in 12.626557s (RW).
2999k/3000k
3000000 bindings found in 18.202100s (RO).
```
> Have smaller fans

- bench/db_bench.ml
- bench/main.ml
Replaced list with array: this decreases the execution time of random
read and write to match the performance of bench/main.ml. However, after
sorting the array, the execution time increases significantly, and it
might not be due to index. Therefore the benchs using an ordered array
should not be compared with the ones on random.
Other changes:
removed file size; print stats for lmdb (in case we want to use it);
print nb of operations / seconds.
> Refactor benchs

- bench/dune
- src/index.ml
- src/index.mli
- test/unix/force_merge.ml
Add a way to get the witness from the index so that it's not required in the `force_merge` signature.
`get_witness` is currently not very nice so review is appreciated.
> Cleaner `force_merge` signature

- src/index.ml
- src/io.mli
- src/io_array.ml
- src/unix/index_unix.ml
> use a toplevel buffer for reads

- index-bench.opam
- index.opam
This directive results in failure when downgrading Dune versions, due to version-specific functionality in the Dune language. See https://github.com/ocaml/opam/issues/3850 for more details.
> opam: remove the 'build' directive on dune dependency

- index.opam
`test/search.ml` has a dependency on `List.init`, which is only
available since `4.06.0`. Tightening this lower bound is sensible,
since the only rev-dep is `irmin`, which already has a lower bound
of `4.06.0`.
> Raise the OCaml lower bound to 4.06

- src/unix/index_unix.ml
- test/unix/main.ml
Fixes (and tests) a bug found by @icristescu: opening a RO instance clears the IO buffer of the corresponding RW instance.
> Fix readonly `v`

- src/unix/pread.c
- src/unix/pwrite.c
To avoid allocating on the stack, keep the runtime lock so that OCaml objects
are not moved around.
This is needed because thread stack are very small on musl<1.1.21 (80k).
Allocating a buffer of 64k bytes on the stack means that the stack overflow
detection (`caml_c_call`) won't have enough space to allocate 32k and will
segfault: see https://github.com/ocaml/ocaml/issues/7490 for a similar bug
report.
`caml_c_call` has been properly fixed in behttps://github.com/ocaml/ocaml/pull/8670
and it also has been changed to only allocate 4k -- also solving our initial
issue with too small thread stacks (as 64+8<80).
Many thanks to @sadiqj for helping with debugging the issue.
Co-authored-by: Frédéric Bour <fred@tarides.com>
> Do not allocate 64k bytes buffers on the thread stack

- bench/dune
- bench/main.ml
- index-bench.opam
Probably very terrible ocaml, and not the best way to split up benchmarks, but it's a start. Eventually we will have regex matching, but for now this works! 
(I spent two days trying to get regex to work, gave up and went the easier route :))
> Breaking up the big bench.

- src/index.ml
`log_async` was not loaded on startup, so here is a patch for this.
instead of loading it (which might cause issues on the next merge because it wouldn't be empty), I copied its data into the `log`.
The code probably requires some factoring, this is only a rough hotfix.
> Load log_async on startup

- CHANGES.md
`dune-release` is always using the first line of the changelog to determine the version tag :(
> Remove changelog title to make dune-release happy

- bench/db_bench.ml
- bench/dune
- bench/main.ml
There's a lot of benchmarks for db!
This PR is mostly trying to separate them so they can be run individually and also moving out the lmdb benchmarks to their own file.
It is ~not~ pretty, and regex would a LOT better solution, but it is also hard :)
> Split db benchmarks

- bench/dune
This should fix the issue described here: https://github.com/mirage/index/pull/143#issuecomment-564592608
Also, that would check that `db_bench` compiles correctly in the CI.
> Build benchs with index-bench instead of index

- CHANGES.md
- bench/db_bench.ml
- src/index.ml
- src/index.mli
- src/unix/index_unix.ml
- src/unix/index_unix.mli
- test/unix/common.ml
- test/unix/common.mli
This splits out a separate API for Index to be used under test. For the moment, the only difference between the two is that `force_merge` is unavailable in the public API: this will allow us to properly test concurrency properties that we don't want to make available to users (see https://github.com/mirage/index/pull/144#discussion_r356645024).
We could also choose to hide other functions, such as `iter`, which we can't give very sensible semantics to currently. I'm interested to know your opinions on this.
> Extract a distinct private API for Index

- index-bench.opam
Left out in #100 because it did not include #146, which checks benchs builds with package `index-bench`.
> Add missing metrics-unix dependency

- src/index.ml
- src/index.mli
- src/io.mli
- src/unix/index_unix.ml
- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/main.ml
In order to prevent weird debug messages during `dune runtest`, we can wait for the merge threads to finish, before exiting a test. 
However, in `index` we do not want to wait for the merge thread to finish, and therefore some debug messages can still appear during a runtest. 
There is an issues in this PR which is that the test `test_fail` does not fail and it should.
> Wait for merge thread to finish in tests

- src/index.ml
- src/io.mli
- src/unix/index_unix.ml
- test/unix/force_merge.ml
When reloading the `log_async`, there is no need to close and reopen the file, as it is not renamed during a merge. This is one of the causes of the difference in performance between a RW read and a RO read. 
`log_async` is reload when the offset of the file changed (due to an `add` or a `clear`) or when the generation changed, and new contents have potentially been added.
> Refactor RO read

- bench/main.ml
- src/index.ml
- src/io.mli
- src/unix/index_unix.ml
It reduces the latency of `replace` when a merge is ongoing.
It regularly reschedules the threads during the merges, allowing the main thread do get some CPU time, because the merging thread used to take all the resources and blocked the main thread for too long.
Tested inside `tezos-node`, new block could take 2 minutes to validate beforehands (because the merging thread was holding the ressources), now it's ~2sec
> Reschedule the threads during merges

- CHANGES.md
- src/index.ml
- src/index.mli
This reverts commit b82dbf3da95c752096e6b174c66cbed7262d7233. The `iter`
API endpoint is relied upon by Irmin in order to do integrity checking,
so it can't be moved to the private API. See
https://github.com/mirage/irmin/pull/904.
> Revert "Move Index.iter to Index.Private.iter"

- index-bench.opam
Index relies on the optional dependency `Logs_threaded`, which was
introduced in `Logs.0.7.0`.
> Constrain Logs to >= 0.7.0

- src/index.ml
- src/index.mli
- src/io.mli
- src/unix/dune
- src/unix/fsync.c
- src/unix/index_unix.ml
Fixes #126.
I'm not sure why this should be an option though, I feel like calling `flush` we expect the content to be... flushed. Exposing some details of our internal caches doesn't feel right to me, and I can't think of a scenario where the use calls `flush` but agrees that some data is still not written to the disk, so this PR calls `fsync` on every `flush`.
Let me know if I got something wrong about it, maybe @samoht you have some insights about it?
> Call `fsync` on `flush`

- bench/dune
- dune-project
- index-bench.opam
- index.opam
- src/dune
- src/unix/dune
- test/unix/dune
Having another go at this, using an explicit dependency on `stdlib-shims` to solve the "abstract `format4`" issue encountered last time (https://github.com/mirage/index/pull/142).
> Make transitive dependencies explicit in dune files

- bench/bench.ml
The pipeline creates a file and then passes the path to the bench target to write the result to. It's better to have the control of creating the file in the pipeline since that can control file permissions, etc.
> Remove file if it already exists.

- CHANGES.md
- src/index.ml
- src/index.mli
- src/io.mli
- src/unix/index_unix.ml
... and parameterise `Index.Make` over a mutex implementation directly.
Decoupling the `IO` and `Mutex` signatures is a step towards simplifying
the `IO` obligation and allows these components to be tested
independently.
> Extract Mutex functionality from the IO signature

- CHANGES.md
- src/index.ml
- src/index.mli
- src/io.mli
- src/unix/index_unix.ml
... and parameterise `Index.Make` over a thread implementation directly.
This is a natural extension of https://github.com/mirage/index/pull/160 (and is based on that PR for convenience). The threading implementation isn't strictly an 'IO' concern.
> Extract Thread functionality from the IO signature

- bench/bench.ml
Before:
```
"results": {
"replace_random": {
"time": 54.639276,
"ops_per_sec": 183018.53047979626,
"mbs_per_sec": 7.854303237524825,
"read_amplification_calls": 0.0007668,
"read_amplification_size": 7.650015317777778,
"write_amplification_calls": 0.0006388,
"write_amplification_size": 10.454485751111111
},
...  
}
```
After:
```
"results": [
{
"name": "replace_random",
"metrics": {
"time": 3.800000000001025e-05,
"ops_per_sec": 2631578.9473677115,
"mbs_per_sec": 112.93511641649916,
"read_amplification_calls": 0.0,
"read_amplification_size": 0.0,
"write_amplification_calls": 0.0,
"write_amplification_size": 0.0
}
},
...
]
```
/cc @gs0510
> Clearer JSON output for benchs

- index.opam
PR https://github.com/mirage/index/pull/169 added a dependency on `mtime` which is not tracked in the `opam` file. (That was actually picked up by the CI at the time, but we missed it...)
> Add missing mtime dependency to opam file

- CHANGES.md
- src/unix/fsync.c
- src/unix/index_unix.ml
- src/unix/index_unix.mli
- src/unix/pread.c
- src/unix/pwrite.c
- src/unix/syscalls.ml
- src/unix/syscalls.mli
This is a step towards: https://github.com/mirage/irmin/issues/1009.
> Expose syscall bindings in the public API

- CHANGES.md
- src/unix/index_unix.ml
It's now no longer necessary to keep the version number as an IO field,
since it will always be equal to `current_version`.
> Fail when Unix IO version number is not as expected

- src/unix/index_unix.ml
- src/unix/index_unix.mli
- src/unix/raw.ml
- src/unix/raw.mli
This extracts the `Raw` module to a `raw.ml` file, and exposes it as
`Private.Raw`. This module is now identical to the one in `Irmin_pack`, so we
might as well pull it from here to stop them from diverging again in future.
Depends on https://github.com/mirage/index/pull/176.
> Extract Raw module

- src/index.ml
- test/unix/main.ml
If generation is `0`  and a clear is called, then the values added after the clear are not detected by an RO instance. 
A simple fix is to always reload the log when generation is `0`.
> Add after clear fails

- src/index.ml
- src/index.mli
- src/unix/index_unix.ml
- test/unix/common.ml
- test/unix/common.mli
- test/unix/dune
- test/unix/force_merge.ml
- test/unix/main.ml
Fix https://github.com/mirage/index/issues/180.
The change is in two parts:
1. generalise threads to return results from children;
1. implement a pre-emptable merge operation (using thread results to propagate the return status of asynchronous merges back to the parent thread).
> Allow merge operations to yield to a concurrent close

- CHANGES.md
- src/index.ml
- src/index_intf.ml
- src/io.mli
- src/unix/index_unix.ml
This PR adds a hook at the end of the merge, to give a change to `irmin-pack` to flush files to disk before the index does. This prevents invalid reads for RO in `irmin-pack`, where a key is found in index but not in pack.
On top of https://github.com/mirage/index/pull/175.
> auto flush callback

- CHANGES.md
- bench/bench.ml
- src/index.ml
- src/stats.ml
- src/stats.mli
As merge is an async operation, I think we have to store a list of the last `n` merges. I picked the last 10 merges, but we can instead have `n` as parameter, if we think its better. 
Every merge operation is timed by default.
> Add timer for merge

- CHANGES.md
- src/index.ml
- src/index_intf.ml
- src/unix/index_unix.ml
- test/unix/force_merge.ml
`is_merging` returns true is the index is running an async merge. 
I used the `merge_lock` to detect that a merge is ongoing. Other operations take this lock (`clear` and `close`), but as they are not async, so it should be fine.
> Add an is_merging function

- CHANGES.md
- README.md
- bench/bench.ml
- index.opam
- src/cache.ml
- src/index.ml
- src/index_intf.ml
- test/cache.ml
- test/dune
- test/main.ml
- test/search.ml
- test/unix/common.ml
- test/unix/common.mli
- test/unix/main.ml
Add a new `Cache.S` signature with two implementations: `Noop` and `Unbounded`. A cache implementation must now be provided to `Index.Make`.
The explicit instance sharing is Implemented with an _optional_ `?cache` argument to `Index.v`, from which the instance may be picked (and to which any new instances will be added). `cache` is perhaps not the best name for this argument: I picked it just because that's the necessary semantics for the underlying datastructure. (`pool`? `sharing_pool`? Ideas welcome.)
> Handle sharing of Index instances explicitly

- index.opam
- test/unix/common.ml
- test/unix/common.mli
- test/unix/dune
- test/unix/force_merge.ml
- test/unix/main.ml
Change `Context.<>` functions to take a continuation representing the test.  After the test is complete, the main index instance and any clones created during the test will be closed. This avoids needing to explicitly `close` various indices for most tests.
This catches quite a few cases where test indices weren't being closed properly.
> Scope test resource lifetimes inside continuations

- CHANGES.md
- src/index.ml
- src/io.mli
- src/io_array.ml
- src/unix/index_unix.ml
- Remove IO.set_generation, IO.get_generation and IO.force_offset
- Change IO.offset to take a `force` arguement
(`IO.offset ~force:true` was `IO.force_offset`,
`IO.offset ~force:false` was `IO.offset`)
- Add `IO.generation`. `IO.generation ~force:true` was `IO.get_generation`
and add `IO.generation ~force:false` to return the cached generation number
> IO refactoring

- CHANGES.md
- src/index.ml
- src/index_intf.ml
- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/main.ml
This only happens when there is an async merge in progress and that the
caches are already full.
Fix #201 
This should probably be the default (and a `close` test should be changed to use `Block_writes`)
> Add an option to choose overcommiting memory instead of blocking writes

- src/index.ml
- src/index_intf.ml
- src/unix/index_unix.ml
- test/unix/force_merge.ml
We want `clear` to be fast and it doesn't matter if we wait for any
async merges to complete as we will empty the entries anyway.
Fix #202
> Index.clear should cancel any concurrent Index.merge

- src/index.ml
- src/index_intf.ml
- test/unix/force_merge.ml
- test/unix/main.ml
This test reproduces the failing test of https://github.com/mirage/index/pull/214, but uses close instead of clear to abort the merge.
The fix is to [not cache buffers](https://github.com/mirage/index/pull/211/files#diff-24b617c6b01eb5122d1e4e45357860c6R180) which is already included in https://github.com/mirage/index/pull/211.
> Test abort merges after one entry added

- .github/workflows/changelog-check.yml
This will enable a GitHub action failing iff `CHANGES.md` was not modified and `no-changelog-needed` tag is not present.
Taken from https://github.com/ocaml-ppx/ocamlformat/blob/6c2524ba7cb737dda647176f47f155b4d74aa90f/.github/workflows/main.yml.
> Add a changelog check

- src/io.mli
- src/unix/index_unix.ml
In the process of working on https://github.com/mirage/index/pull/219, I noticed that there are quite a few unused IO endpoints. This removes them.
> Remove unused IO fields

- src/unix/raw.ml
`@tailcall` annotations are unstable under inlining by the compiler, causing this code to fail on `+flambda` switch variants.
Fixes an error in the CI on `master`.
> Remove broken @tailcall annotation

- src/index.ml
- test/unix/common.ml
I noticed while running layered store benchmarks, that the log_async file is read from scratch at every sync call. This is because, if the generation of log_async differs from the generation of the instance then log_async is [refilled from offset 0](https://github.com/mirage/index/blob/master/src/index.ml#L271). With the overcommit option, the log_async can get quite large, so this sync from scratch can take a lot of time (2s in my benchs for every RO sync call). 
This PR is an effort to make the generations consistent between log and log_async, and this makes my benchmarks better. However, it is hard to add test for this, and we do not yet have benchmarks in index that use both RW and RO instances to spot the regression.
> Fix generation of log_async

- src/index.ml
This reverts commit 342be45501e08c4901e879a2cd2e2a34f16d1e6c from PR #226, as it introduced a bug. To test and keep track of this issue we have #227 opened.
> Revert 226

- index.opam
- test/fuzz/fan/dune
- test/fuzz/fan/main.ml
Just picking the printers from version 0.2.
Also increasing the memory limit as the default 50MB won't be enough for these tests and will trigger (out of memory) errors.
> Use crowbar.0.2

- CHANGES.md
- src/index.ml
This will prevent values from being added to the log before the log_async is cleared, as those values could possibly be discarded on next startup if a crash occured and the log_async was considered not empty.
> Move log_async clear under rename_lock.

- CHANGES.md
- src/index.ml
- src/io.mli
- src/layout.ml
- src/layout.mli
- src/unix/index_unix.ml
... and remove calls to `Sys.file_exists` inside the `index` package, which is supposed to be platform-agnostic.
Also extracts namespacing choices to a new module, `Layout`. This will be more obviously useful when we add integrity-checking utilities that must know about the FS structure without necessarily relying on the entire implementation of Index.
> Add IO.exists

- CHANGES.md
- src/index.ml
- src/index_intf.ml
- test/unix/force_merge.ml
- test/unix/main.ml
When developing the offline integrity-checking tool for Index, I noticed that the following simple usage of Index is non-deterministic:
```ocaml
let random () =
let index = Index.v ~fresh:true ~log_size:100 "data/random" in
for _ = 1 to 1001 do
Index.replace index (random ()) (random ())
done;
Index.close index
```
In particular, the `Index.close` call may or may not cancel an ongoing merge operation, meaning that we cannot know what files will exist on disk after running this code. After pondering on it for a bit, I think this behaviour of `close` should be opt-in. This PR does exactly that.
> Make Index.close merge termination logic opt-in

- src/index.ml
- src/index_intf.ml
Small cleanup to get rid of a few duplicated types and signatures.
Depends on https://github.com/mirage/index/pull/234.
> Deduplicate private signature definitions

- src/fan.ml
- src/fan.mli
- src/index.ml
- test/fuzz/fan/main.ml
The `Fan` module only works with the following workflow:
- Do a lot of `update`
- Do a `finalize`
- Do a lot of `search`
This PR makes this workflow appear in the types and ensures the invariant is verified.﻿
> Add capabilities to the fanout

- Makefile
The pipeline can use a standard `make bench` across all different projects now!
> Add bench target to Makefile.

- index.opam
- src/index.ml
- src/index_intf.ml
- src/unix/dune
- src/unix/index_unix.ml
- test/unix/common.ml
- test/unix/common.mli
- test/unix/dune
- test/unix/flush_callback.ml
- test/unix/force_merge.ml
- test/unix/main.ml
Our usage of the `Mutex` module in the UNIX implementation of Index previously relied upon undefined behaviours of `glibc`, which caused Index to be incompatible with FreeBSD. In particular, we were relying on being able to release a mutex from a thread that did not itself take the mutex (in order to implement the merge lock).
This commit replaces the usage of `Mutex` with a dependency on the `semaphore-compat` library, which provides a shim of the `Semaphore` module to be released in OCaml 4.12. In particular, the mutual-exclusion semantics that we require are provided by the binary semaphores in this library.
> Use Semaphore compatibility library

- src/checks.ml
- src/checks_intf.ml
- test/cli/index-fsck-help.txt
This is the `index` counterpart of https://github.com/mirage/irmin/pull/1141, working towards pulling these endpoints together in a `tezos-node storage` subcommand.
> Expose Cmdliner terms of the integrity-checking binary

- src/io_array.ml
The prefetched area should not exceed 4096 in most cases, thanks to the fan out. However, if the hash function is not well distributed, some exceptions might happen where the prefetched area actually exceeds 4096.
As long as this excess is reasonable (x2), we still want to prefetch (and not issue a warning).
> Increase prefetch warning limit

- .ocamlformat
Hi, this pull-request is a preview of the soon to be released ocamlformat.0.16.0. I'm glad to see there is no diff at all so far.
> Preview of ocamlformat.0.16.0

- CHANGES.md
- src/index.ml
- src/index_intf.ml
Experimenting with adding more control over merges from the freeze thread in irmin-pack. For now the irmin-pack benchmarks look promising:
- the spikes are the freezes that block waiting for previous freeze to complete
- if we remove the spike due to freezes and only look at the time for the rest of the commits:
On top of https://github.com/mirage/index/pull/251.
> Add an overcommit option in replace to postpone merges

- src/index.ml
Print:
[INFO] index [upper1] merge completed { id = 3; duration = 9.65s }
Instead of:
[INFO] index [completed] merge upper1 { id = 3; duration = 9.65s }
> Fix info message

- CHANGES.md
- src/index.ml
- src/index_intf.ml
- test/unix/common.ml
- test/unix/force_merge.ml
- test/unix/main.ml
[try_merge] will not trigger if the log limits have not been reach.
Use [try_merge ~force:true] to match the previous behavior.
> Rename Index.force_merge into Index.try_merge

- CHANGES.md
- index.opam
- src/dune
- src/fan.ml
- src/fan.mli
- src/index.ml
- test/fuzz/fan/dune
- test/fuzz/fan/main.ml
On 64-bit systems, this should reduce the memory usage of the fan-out by a factor of 4.
> index: use 63-bit integers in the fanout

- index.opam
- src/checks.ml
- src/fan.ml
- src/fan.mli
- src/index.ml
- src/io.ml
- src/io_array.ml
- src/io_intf.ml
- src/search.ml
- src/search_intf.ml
- src/unix/dune
- src/unix/index_unix.ml
- src/unix/pread.c
- src/unix/pwrite.c
- src/unix/raw.ml
- src/unix/raw.mli
- src/unix/syscalls.ml
- src/unix/syscalls.mli
- test/dune
- test/fuzz/fan/main.ml
- test/search.ml
- test/unix/dune
- test/unix/io_array.ml
Fix https://github.com/mirage/index/issues/285.
Currently using an unreleased feature in `optint` to allow observing the type equality without a coercion. Very slightly faster than using the (identity) cast, which doesn't seem to be inlined w/o Flambda 2.
> Use 63-bit integers as file offsets

- bench/bench.ml
The CB UI currently has no satisfying solution for reporting a list of values, and it only takes the fist value of the list when reporting.
This PR reports the cumulated merging time instead of the list of durations.
> Benchmarks: report cumulated merges duration instead of list

- bench/bench.ml
This bench flushes the idnex after each `replace`, this is not a behaviour that we use in production, so we can ignore this in quick mode.
> benchs: `replace_random_sync` in slow mode only

- CHANGES.md
- src/checks.ml
- src/index.ml
- src/io_intf.ml
- src/unix/index_unix.ml
- src/unix/raw.ml
- src/unix/raw.mli
- test/unix/io_array.ml
extracted from https://github.com/mirage/index/pull/288.
I'm still not sure how the flaky tests in https://github.com/mirage/index/issues/268 and https://github.com/mirage/irmin/issues/1245 occur, but one possible explanation is that the readonly tries to read the header  of a file while that header is not yet written. This can happen if the file is being created simultaneously to a readonly trying to do a sync. 
This PR introduces a `v_readonly` that 
- eliminates the two steps (1) check if file exists and (2) then open it (the file might disappear between the two depending on how we implement `clear` );
- allows readonly to read the header - if the header is not yet written then readonly "acts" as if the file is not yet created.
I'm not sure we want to do this though (and we don't …
> Specialise `v` to readonly and readwrite instances

- src/io_intf.ml
- src/unix/index_unix.ml
Expose in `IO` a function to get the size of the header of `data`. This necessary to implement a migration protocol from `data` towards another storing format (namely, for btrees).
> expose header size

- CHANGES.md
- src/data.ml
```ocaml
(* Entry *)
let encode' key value f =
f (K.encode key);
(* Flush possible. Crash-consistency bug *)
f (V.encode value)
```
Called like this:
```ocaml
Entry.encode' key value (IO.append t)
```
with
```ocaml
let append t buf =
Buffer.add_string t.buf buf;
flush t (* if offset is high enough *)
```
This means that the encoding function takes a writing function `f` and applies it to the encoding. If this function `f` flushes a flush may occur and if a crash happens at the same time the flushed encoding will be incomplete (the key will have been written but not the value)
The easiest way to prevent it is to call `f` on the concatenation of the two encoding since this won't induce any API change.
Since `Repr.encode` will change in a near future, the priority is to fix this bug and work …
> Crash-consistency bug fix

- CHANGES.md
- src/index.ml
- src/index_intf.ml
- src/io_intf.ml
- src/unix/index_unix.ml
- test/cli/stat.t/run.t
- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/main.ml
After a `clear` the files on disk should only contain the header  
For now this only works (and is tested) for the `data` file.
> Remove files on disk on `clear`

- src/index.ml
This avoid multiple readers modifying the state concurrently.
Note: I am not sure it's a real issue, but as this is the only function modifying `t.generation` `t.log` and `t.log_async` for read-only instances, so it's probably a good idea to make sure we do this safely. We need to see the performance implication as now all the concurrent sync calls will be gated on that lock.
> protect sync with a lock

- src/index.ml
- src/io_intf.ml
- src/unix/index_unix.ml
- test/cli/stat.t/run.t
- test/unix/main.ml
We don't need to create a temporary file, it's fine to just remove
the initial file while holding an open file descriptor on the resource.
We also can directly remove the files which are not needed after a clear:
only the log file is needed as it contains the current generation number.
> Simplifications on top of #288

- .gitignore
This happens when using `opam switch link`.
> Gitignore opam/ even if it's a symlink

- src/data.ml
- src/index.ml
This has no effect on passing tests, but causes failing ones to behave more sensibly in the short term. A more complete solution would fix https://github.com/mirage/index/issues/284 entirely.
> index: release the merge lock if a merge raises an exception

- CHANGES.md
- src/index.ml
- src/index_intf.ml
- test/unix/main.ml
Do not reload log_async on every sync
In general `generation(log_async)` is `generation(log) + 1`. So a read-only instance needs to reload a the `log_async` file only if the diff > 2.
There is also a small race between sync and merge: Merge is performing `clear(log)` then `clear(log_async)` which both bump the generation number. Between these two clears, `generation(log_async) = generation(log)`. So the sync operation also checks if the diff is > 1 and if a `clear(log_async)` has just completed (clear sets `offset` to 0 and unlink the file so noone else could write on it).
Fix #296
> Do not reload log_async on every sync

- CHANGES.md
- src/unix/index_unix.ml
Not totally sure about this one: this will probably slow down single writer/multiple instances within the same process (but probably not much as this is not a very common operation) ; but that'll speed up signalling of when a merge is done for other processes opened in read-only mode.
> use fsync to flush metadata when reoperning a file with new headers

- .ocamlformat
- CHANGES.md
- src/checks.ml
- src/data.ml
- src/index.ml
- src/index_intf.ml
- src/io_intf.ml
- src/unix/index_unix.ml
- test/cli/stat.t/run.t
- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/io_array.ml
- test/unix/main.ml
The 1.3.1 release contains:
- fix for potential race(s) between clear (e.g. merge) and sync
- fix for potential race(s) between syncs
- improved update latency for sync just after a merge
- performance improvements for syncs happening at the same time as blocking merges
- proper resource cleanup when a merge fails
- unlink unused files after a merge/clear
- a minor crash consistency fix
- reduced allocations during merge
> Prepare 1.3.1

- .gitmodules
- CHANGES.md
- bench/common.ml
- bench/dune
- bench/replay.ml
- dune
- index-bench.opam
Initial benchmarks for replaying the trace of index operations during bootstrap. The trace is small for now, I’m working on getting a bigger one.
It needs the dependency on `tezos-context-hash` but only on the Hash module, and it needs to be in a separate package (https://github.com/icristescu/tezos-context-hash/tree/hash_pkg); Otherwise, we end up with the following dune error:
```
Error: Conflict between the following libraries:
- "index" in _build/default/src
- "index" in /Users/icristes/.opam/4.11.0/lib/index
-> required by library "irmin-pack" in
/Users/icristes/.opam/4.11.0/lib/irmin-pack
-> required by library "tezos-context-hash" in
_build/default/vendors/tezos-context-hash/src
-> required by executable replay in bench/dune:25
```
> Replay bootstrapping trace

- src/import.ml
- src/index.ml
- src/io.ml
- src/io_array.ml
Fixes the bug spotted here: https://github.com/mirage/index/pull/312#discussion_r622221691 (not that anyone's likely to have run into it). I think `Int63.to_int` is a little too tempting from an API perspective, so I've shadowed it and provided more clearly named checked and unchecked alternatives.
> Raise exceptions on failed Int63.to_int coercions

- CHANGES.md
- bench/bench.ml
- bench/common.ml
- bench/dune
- bench/replay.ml
- index-bench.opam
- src/checks.ml
- src/checks_intf.ml
- src/dune
- src/import.ml
- src/index.ml
- src/index_intf.ml
- src/io_intf.ml
- src/platform.ml
- src/stats.ml
- src/stats.mli
- src/unix/index_unix.ml
- test/cli/stat.t/run.t
- test/unix/common.ml
- test/unix/dune
- avoid using `Sys.time` to measure durations;
- avoid dependency on `mtime.clock.os` in Index core by functorising over a time source.
... and does some minor refactoring to extract `Logs` boilerplate and cleanup.
Fix https://github.com/mirage/index/issues/314.
> Refactor use of monotonic time in Index

- CHANGES.md
- Makefile
- bench/bench.ml
- bench/dune
- bench/replay.ml
- src/index.ml
Fan warning is invoked when the fan-out is double in size
The log reporter is quiet by default when using `make bench` and shall
be invoked with `--verbosity {error | warning | info | debug}`
> Fan warning and bench updated with a log reporter

- CHANGES.md
- src/io_array.ml
The current setting is probably a bit too defensive, as unevenly distributed keys happens quite often in practice.
> Release the prefetch warning threshold

- src/index.ml
- src/io_intf.ml
- src/unix/buffer.ml
- src/unix/buffer.mli
- src/unix/index_unix.ml
The merge process loads entries from the old data file into a buffer before writing them out to the new one. Previously, individual entries were then copied to a second buffer before writing, but this isn't necessary: the IO can simply read substrings from the first one directly.
> Avoid using an intermediate scratch buffer in the merge

- CHANGES.md
- src/index.ml
In the event that the `log_async` headers change unexpectedly when attempting a sync, we can attempt a recovery by reloading the entire `log` from scratch (as this may contain new updates).
In principle, this case should never occur, but the previous `assert false` has been triggered via Tezos at least once (https://gitlab.com/tezos/tezos/-/issues/1403), and the failing node was able to recover on restart.
> Attempt to recover from a broken IO header invariant

- index-bench.opam
- index.opam
Constrain the version of progress to `0.1.1` until https://github.com/CraigFe/progress/issues/12 is fixed, and until we upgrade index's code
Cc @CraigFe
> Constrain progress version

- src/unix/index_unix.ml
As of `4.13.0~alpha`, function applications on the left-hand-side of an application of `( @@ )` are rejected as not tailcalls.
> Avoid flaky usage of [@tailcall]

- CHANGES.md
- src/index.ml
- src/index_intf.ml
- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/main.ml
> Closing merge file_descr when aborting

- CHANGES.md
- src/index.ml
On startup, we transfer entries from log_async to log. Make sure to call fsync here so that persisted entries in log_async continue to be persisted in log.
> Add an fsync after flushing the log file on startup

- CHANGES.md
- src/index.ml
This backports https://github.com/mirage/index/pull/329 to the 1.3.x series of Index releases.
Corresponding opam-repository PR: https://github.com/ocaml/opam-repository/pull/19137.
> Prepare 1.3.3 release

- src/index.ml
- test/unix/io_array.ml
- test/unix/main.ml
The recently-released `fmt.0.8.10` deprecates this function in favour of `Fmt.str`.
> Avoid usage of `Fmt.strf`

- CHANGES.md
- src/data.ml
- src/index.ml
- src/log_file.ml
- src/log_file.mli
- src/small_list.ml
- src/small_list.mli
- src/unix/buffer.ml
- src/unix/buffer.mli
- src/unix/index_unix.ml
This implements "Suggestion 2" as described in https://github.com/mirage/index/issues/354, without adding an LRU.
Fix https://github.com/mirage/index/issues/354.
> Reduce the memory usage of the write-ahead log

- src/log_file.ml
https://github.com/mirage/index/pull/355 introduced a small optimisation to re-use a "local" scratch buffer when decoding values from the log file.
This is actually unsafe: during the merge, the asynchronous merge thread and the main writer thread can attempt concurrent reads from the log file, causing contention over the scratch buffer. This can be observed by inserting `Thread.yield` calls inside the `Value.decode` implementation and then stress-testing the interface (e.g. by running the replay benchmarks).
This commit ensures that each call to a `Log_file` function gets its own scratch buffer, ensuring safe concurrent access without introducing potential contention issues.
_Note: I initially tried to just wrap `t.scratch_buf` in a mutex …
> index: avoid unsafe buffer sharing in `Log_file`

- CHANGES.md
- index.opam
- src/dune
- src/index.ml
- src/index_intf.ml
- src/stats.ml
- src/stats.mli
- test/unix/common.ml
- test/unix/common.mli
- test/unix/main.ml
- test/unix/test_lru.ml
Fix https://github.com/mirage/index/issues/359.
Following the recent change to the log-file implementation, successful reads of the index must always read from disk (because even log file entries are not kept entirely in memory). This traded some speed performance in favour of much lower memory usage.
For workflows with temporal locality, it's possible to recover some of this speed by adding a relatively small LRU to cache `find`s from disk. This is implemented by this commit.
**TODO**:
> index: use an LRU to cache reads

- src/unix/raw.ml
- src/unix/raw.mli
Irmin's IO implementation no longer requires a generation header, so this commit adds separate functions for reading the "offset + version" prefix of the supported headers.
> unix: add `Raw.Header_prefix` module for use by `irmin-pack`

- .ocamlformat
- test/cli/generate.ml
- test/cli/index_fsck.ml
This is a preview of the not-yet-released `ocamlformat.0.20.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.
The changes are due to an improvement of the formatting of functor arguments.
> Upgrade to ocamlformat.0.20.0

- .ocamlformat
`ocaml-version` must come after `profile`, since the `profile` option resets all options to the profile defaults.
See https://github.com/mirage/irmin/pull/1556#issuecomment-1019929899.
> Fix OCamlformat option ordering

- CHANGES.md
- bench/dune
Fixes #388 
As discussed with @icristescu and @Ngoguey42, the package is not meant to be used by external users nor is running the benchmark so we agreed that making it private was the right move here.
> Make index-bench bench executable private

- index.opam
This is not required anymore since #386!
> Remove unecessary upper bound on cmdliner

- CHANGES.md
- src/unix/index_unix.ml
This simple PR aims to open lock files with the `Unix.O_CLOEXEC` flag to avoid resource leak in case of forks.
> Open lock files with O_CLOEXEC flag

- CHANGES.md
- bench/bench.ml
- bench/replay.ml
- index-bench.opam
- index.opam
- src/checks.ml
pin-depends crowbar for
- https://github.com/stedolan/crowbar/pull/64
> Update to cmdliner.1.1.0

- .ocamlformat
- CHANGES.md
- bench/bench.ml
- bench/dune
- bench/replay.ml
- src/checks.ml
- src/checks_intf.ml
- src/dune
- src/index_intf.ml
- src/log.ml
- src/log.mli
- src/platform.ml
- src/unix/buffer.ml
- src/unix/dune
- src/unix/index_unix.ml
- src/unix/index_unix.mli
- src/unix/raw.ml
- test/cli/dune
- test/unix/common.ml
- test/unix/dune
Small refactoring to allow `index` to be used on MirageOS (with [notafs](https://github.com/tarides/notafs)) by removing the accidental dependency on unix coming from progress and fmt_tty
> Mirage support: make unix dependency optional

- test/unix/dune
- The upcoming release of logs.0.8.0 (https://github.com/ocaml/opam-repository/pull/27602) installs `logs.threaded` in `<dst-dir>/logs/threaded`
- Previously the tests in `tests/unix` would only find this library by chance, since `logs_threaded.cm*` was installed in the same directory as the `logs` library
> tests/unix: add `logs.threaded` as a dependency

- bench/bench.ml
- bench/dune
- index-bench.opam
- test/unix/dune
Fix https://github.com/mirage/index/issues/401 (and a few other dependency names in dune files)
> Update for cmdliner.2.0.0
