- src/index.ml
- src/io.mli
- src/unix/index_unix.ml
Detect log changes (eg another process writing things) when the index is in read-only mode.
> Detect log changes

- src/index.ml
And use types to make sure this won't happen again.
> fix sharing

- src/index.ml
> Fix remaining Tbl.replace

- src/index.ml
This will ease further improvements.
> Refactoring : Have a separate module for the fanout

- src/index.ml
`iter_io f io` could go further than `IO.offset io` when the page size was larger than the actually remaining valid offset. This causes problems when data actually exists beyond `IO.offset io`.
Should fix issues in https://github.com/mirage/irmin/pull/826
> Do not allow iter_io to go further than IO.offset

- src/index.ml
Group index and fan_out together in an option.
This way we can keep the integrity invariant that `fan_out` is in sync with the file, and allows better handling of initialization.
> Have a separate index type

- bench/main.ml
- src/fan.ml
- src/fan.mli
- src/index.ml
- src/index.mli
- test/unix/main.ml
> Drop `~fan_out_size` and automatically compute it instead

- src/index.ml
- src/io.mli
- src/unix/index_unix.ml
Added a close function to the IO module.
> Add close function

- src/index.ml
Before:
```
Adding 3000000 bindings.
2999k/3000k
3000000 bindings added in 18.889829s.
...
```
After:
```
Adding 3000000 bindings.
2999k/3000k
3000000 bindings added in 14.619115s.
...
```
e.g. ~25%  improvements of the merge speed.
> batch reads during merges

- src/fan.ml
- src/index.ml
> Some code suggestions

- src/index.ml
Resolve https://github.com/mirage/index/pull/38#discussion_r317804953
> ensure that reads have the right size

- test/unix/main.ml
> Use a hashtbl instead of a list in the tests

- bench/main.ml
- src/index.ml
- src/index.mli
- test/unix/main.ml
Built on top of #46 for convenience.
> Do not allow duplicate keys anymore

- src/unix/index_unix.ml
Minor renamings, I think this is useful for clarity and helps in case we want to add more of these headers (e.g. a fanout).
> Move version/offset/generation to submodules

- src/index.ml
- src/index.mli
- test/unix/common.ml
- test/unix/dune
- test/unix/force_merge.ml
- test/unix/main.ml
Expose a force merge in the API and add tests
> Expose merge for testing

- src/unix/index_unix.ml
> Open files with O_CLOEXEC

- src/index.ml
- test/unix/main.ml
> Read after clear does not fail

- .gitignore
- test/unix/force_merge.ml
- test/unix/main.ml
> Move test indices to _tests/unix.main

- README.md
- src/index.mli
This resolves #68.
Have kept the README fairly sparse for now, since the library is reasonably WIP. I suggest adding more details (documentation pointers, etc.) once the IO signature is a little more stable.
> Add README

- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/io_array.ml
- test/unix/main.ml
Makes many of the Unix tests individually executable.
> Refactor tests

- test/unix/main.ml
Closing the index is only used in the Close module, otherwise some of these tests overlap.
> Restart tests do not close the index

- bench/common.ml
- bench/common.mli
- bench/db_bench.ml
- bench/dune
- bench/main.ml
- src/unix/index_unix.ml
- src/unix/index_unix.mli
Similar to the ones in LevelDB and RocksDB.
> Benchmarks

- .gitignore
- .travis.yml
- index-bench.opam
- test/dune
- test/fuzz/fan/dune
- test/unix/dune
> Add index-bench.opam file

- dune-project
- index-bench.opam
- index.opam
Dune's new version has some fancy features which might be useful down the line, hence upgrading the version.
> Upgrade dune version.

- src/index.ml
I found myself wondering what this variable is. The new name will ease maintenance.
> Rename `counter` to `open_instances`

- test/unix/force_merge.ml
- test/unix/log.ml
- test/unix/log.mli
> test: skip file-descriptor test if lsof is unavailable

- src/index.ml
We don't need to keep so much information in memory.
- `key` is already the key of the `Tbl.t`, no need to keep it in the value too.
- `key_hash` is only useful during merges, so we can compute it at this time only.
Bonus: now `Tbl.find` has the same return type as `interpolation search`.
> Use `value Tbl.t` instead of `entry Tbl.t`

- bench/db_bench.ml
- bench/db_bench.mli
- bench/main.mli
LMDB and index can be benchmarked separately
> Separate lmdb and index benchmarks

- src/index.ml
- src/search.ml
- src/search.mli
- src/unix/dune
- src/unix/index_unix.ml
- test/search.ml
The goal is to have more logs, in a more consistent way.
> Review the use of logs

- test/search.ml
See https://github.com/mirage/index/pull/118#discussion_r343146533. I have manually verified that this test exposes such bugs.
> Test interpolation_search for a constant metric function

- src/fan.ml
- src/fan.mli
- src/index.ml
- src/index.mli
- src/io.mli
- src/io_array.ml
- src/io_array.mli
- src/log.ml
- src/log.mli
- src/search.ml
- src/search.mli
- src/unix/index_unix.ml
- src/unix/index_unix.mli
All contributors, in alphabetical order.
> Add license headers

- test/search.ml
I forgot to rebase before merging, leading to a bad merge.
> Fix an issue during #118 git merge

- CHANGES.md
- index.opam
These changes make `dune-release lint` happy
> Prepare the release

- bench/main.ml
> benchmarks: refactor the benchmark split

- src/index.ml
- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/main.ml
Similarly to `close` in Irmin-pack.
> Clear log mem on close

- bench/db_bench.ml
So as to prevent erasing other files in the `db_bench` directory.
> Refactor the clean up operation in db_bench

- bench/common.ml
- bench/common.mli
- bench/db_bench.ml
- bench/dune
- bench/main.ml
- index-bench.opam
> Add the option to write stats as a json output.

- bench/db_bench.ml
Based on https://github.com/mirage/index/pull/100
> Force merge bench

- CHANGES.md
Including references to improvments made by
https://github.com/mirage/index/pull/141 and
https://github.com/mirage/index/pull/152.
> Update CHANGES in preparation for 1.0.2 release

- CHANGES.md
- src/index.ml
- src/index.mli
- test/unix/main.ml
> Add filter

- src/index.ml
See https://github.com/mirage/index/pull/172#issuecomment-627237818.
(Thanks @icristescu for finding this again!)
> Fix creation when index is present but empty

- CHANGES.md
Also added the changelog entry for #183.
> Prepare 1.2.1 release

- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/main.ml
Culprit: https://github.com/mirage/index/pull/185
> Fix broken rebase during merge of #185

- bench/bench.ml
Running all the benchmarks is time intensive and also space-intensive.
These minimal benchmarks will be faster to run on PRs and since currently the
way to filter benchmarks is regex-based this commit introduces a new list to
run these minimal benchmarks.
> Add minimal bench target

- src/index.ml
This doesn't change the semantics of the existing code (bug fixes are coming next)
> Minor refactoring of Index.sync

- CHANGES.md
- src/index.ml
- src/io.mli
- src/io_array.ml
- src/unix/index_unix.ml
Adding another layer of caching is actually not necessary 🎉
> Revert 207

- CHANGES.md
- src/index.ml
- test/unix/main.ml
Related to #200
The failure is not fully reproducible, I still have no clue of what is happening.
> Fix the race between merge and sync

- src/unix/index_unix.ml
That doesn't change anything, but that makes the logs a bit prettier
> Index.rename should also rename the cached filename

- src/index.ml
- test/unix/force_merge.ml
- test/unix/main.ml
Fixes a bug where the log would grow without bound when using `` ~throttle:`Overcommit_memory ``, since implicit merges were avoided even when they would be non-blocking.
> Ensure that non-blocking merges are triggered when overcommitting memory

- test/unix/common.ml
We had some test failures in the throttle tests in the case of `Overcommit_memory` (see for instance [here](https://ci.ocamllabs.io/github/mirage/index/commit/2772fe143aa4794e1027f2717e41f2b2014a3908/variant/centos-8-4.11)).
This happened because the tests assumes that `Context.full_index` provides a 'clean' (fully merged) index, which was possible to ensure by counting how many elements were added in normal mode; but is not is not possible without explicitly merging in overcommit mode.
That PR explicitly merges the index in `Context.full_context` before returning it.
> Fix throttle test

- test/unix/main.ml
The asynchronous merging thread must wait for the parent to signal the merge before it can proceed, otherwise it might finish the merge before the parent thread gets a chance to issue the abort.
> Fix race condition in Close.abort_merge test

- index.opam
These packages have now all been released.
> Remove unnecessary pin-depends

- src/unix/index_unix.ml
Same as https://github.com/mirage/irmin/pull/1144
> index: use Int64 intrisics in the hot loop

- src/index.ml
- src/stats.ml
- src/stats.mli
As requested by @icristescu in https://github.com/mirage/index/pull/251.
> Add log messages at the end of merges

- src/index.ml
Try to keep only two info messages per merge (start and end events)
> improve info message

- index.opam
Needs https://github.com/ocaml/opam-repository/pull/17852 to be merged first.
> add constraints to repr>=0.2.0

- CHANGES.md
Upstream PR @ https://github.com/ocaml/opam-repository/pull/17922.
> Release 1.3.0

- src/unix/raw.ml
Should help in diagnosing https://github.com/mirage/index/issues/268.
> Improve information given by failing assert statements in IO

- .ocamlformat
This is a preview of the not-yet-released ocamlformat.0.17.0, please wait until the package is published in opam to merge this PR.
> Preview: upgrade to ocamlformat.0.17.0

- src/index.ml
This adds some documentation throughout of the code. The codebase is quite complicated to get into, and not documented at all.
It's not finished yet, but I expect we can iterate a little bit before merging, so reviewing is already welcome.
I'm happy to remove some comments if they are too verbose or noisy.
> Internal documentation

- index.opam
- src/cache.ml
- src/checks.ml
- src/checks_intf.ml
- src/data.ml
- src/fan.ml
- src/fan.mli
- src/import.ml
- src/index.ml
- src/index_intf.ml
- src/io.ml
- src/io_array.ml
- src/io_array.mli
- src/io_intf.ml
- src/layout.ml
- src/layout.mli
- src/log.ml
- src/search.ml
- src/search_intf.ml
- src/stats.ml
- src/stats.mli
- src/unix/import.ml
- src/unix/index_unix.ml
- src/unix/index_unix.mli
- src/unix/raw.ml
- src/unix/raw.mli
- src/unix/syscalls.ml
- src/unix/syscalls.mli
For consistency w/ what we're now doing in Irmin.
> Use an `import.ml` file rather than aliasing `Optint.Int63`

- src/unix/pread.c
- src/unix/pwrite.c
> Bugfix: int file offsets are Long_val, not Int_val

- test/unix/force_merge.ml
PR https://github.com/mirage/index/pull/226 introduced a bug, reproduced by the test `sync_before_and_after_clearing_async`. The issue is when the end of a merge interleaves with two RO sync calls. 
It did not occur before #226 because the generation of log_async was [log's generation+1](https://github.com/mirage/index/pull/226/files#diff-732d381615307f94d510e2dbdee74f4aL683). This ensured that between the two RO sync there was a generation change for log_async, but lead to inconsistent generations between log and log_async. As mentioned in #226 this is a problem: the log_async file is read from scratch even when it is not necessary. 
One simple solution is to remove the [assert](https://github.com/mirage/index/pull/226/files#diff-732d381615307f94d510e2dbdee74f4aL683) and treat `offset > …
> Test generation updates of log_async

- CHANGES.md
- Makefile
- bench/bench.ml
The displayed result is the mean of all the computed results
> Updated the benches to allow multiple executions

- .ocamlformat
- bench/bench.ml
- src/cache.ml
- src/checks.ml
- src/data.ml
- src/fan.ml
- src/index.ml
- src/io_array.ml
- src/io_array.mli
- src/io_intf.ml
- src/layout.ml
- src/layout.mli
- src/log.ml
- src/search.ml
- src/search_intf.ml
- src/stats.ml
- src/stats.mli
- src/unix/index_unix.ml
- src/unix/index_unix.mli
- src/unix/raw.ml
- src/unix/raw.mli
- test/cache.ml
- test/fuzz/fan/main.ml
- test/search.ml
- test/unix/common.ml
- test/unix/common.mli
- test/unix/force_merge.ml
- test/unix/io_array.ml
- test/unix/log.ml
- test/unix/main.ml
... for consistency with Irmin and Repr.
> OCamlformat: module-item-spacing = compact

- src/index.ml
- src/unix/index_unix.ml
> Simplify clear again

- bench/common.ml
- bench/dune
- bench/replay.ml
- index-bench.opam
- index.opam
- src/checks.ml
- src/dune
- src/import.ml
- src/io_array.ml
Let's wait for `progress=0.2.1` before merging
> Upgrade progress library version

- CHANGES.md
The update in #326 was not added to the right section
> Fix CHANGES

- .ocamlformat
- src/cache.ml
- src/fan.ml
- src/fan.mli
- src/index.ml
- src/index.mli
- src/index_intf.ml
- src/io.ml
- src/io.mli
- src/io_array.ml
- src/io_array.mli
- src/log.ml
- src/log.mli
- src/search.ml
- src/search.mli
- src/search_intf.ml
- src/unix/index_unix.ml
- src/unix/index_unix.mli
This is a preview of the not-yet-released `ocamlformat.0.19.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.
> [Preview] Upgrade to ocamlformat.0.19.0

- bench/replay.ml
- index.opam
> Adapt to mirage/repr#81 (improved binary decoder type)

- .ocamlformat
- CHANGES.md
- bench/bench.ml
- bench/replay.ml
- src/checks.ml
- test/cli/dune
similar to https://github.com/mirage/irmin/pull/1803
also upgrade OCamlFormat
> Support all versions of cmdliner

- CHANGES.md
corresponding opam PR https://github.com/ocaml/opam-repository/pull/21488
> Release 1.6.1
